
export const KafkaTopics = {

    SUBMISSION_JOBS : 'SUBMISSION_JOBS',
    SUBMISSION_RESULTS : 'SUBMISSION_RESULTS',

    RUN_JOBS : 'RUN_JOBS',
    RUN_RESULTS : 'RUN_RESULTS',

    CUSTOM_JOBS : 'CUSTOM_JOBS',
    CUSTOM_RESULTS : 'CUSTOM_RESULTS',

    RETRY_QUEUE : 'RETRY_QUEUE',
    DLQ_QUEUE : 'DLQ_QUEUE',

} as const