
export const KafkaConsumerGroups = {

    CM_SUB_NORMAL_EXEC : 'CM_SUBMISSION_NORMAL_EXEC',
    CM_SUB_BATTLE_EXEC : 'CM_SUBMISSION_BATTLE_EXEC',
    CM_SUB_NORMAL_RESULT : 'CM_SUBMISSION_NORMAL_RESULT',
    CM_SUB_BATTLE_RESULT : 'CM_SUBMISSION_BATTLE_RESULT',

    CM_RUN_NORMAL_EXEC : 'CM_RUN_NORMAL_EXEC',
    CM_RUN_BATTLE_EXEC : 'CM_RUN_BATTLE_EXEC',
    CM_RUN_NORMAL_RESULT : 'CM_RUN_NORMAL_RESULT',
    CM_RUN_BATTLE_RESULT : 'CM_RUN_BATTLE_RESULT',

    CM_CUSTOM_NORMAL_EXEC : 'CM_CUSTOM_NORMAL_EXEC',
    CM_CUSTOM_NORMAL_RESULT : 'CM_CUSTOM_NORMAL_RESULT',


} as const